name: UHC
version: 1.0
main: me.archietech.com.uhc.UHC
api-version: 1.18
authors: [ alessandroDeIturbe, _AdryTech_ ]
description: A Spigot-Minecraft plugin for UHCs
commands:
  start:
    description: Run uhc command
    usage: /<start>
    aliases: s
    permission: uhc.ops
    permission-message: You do not have permission to use this command.
  setup:
    description: setup world for uhc
    usage: /<setup>
    aliases: set
    permission: uhc.ops
    permission-message: You do not have permission to use this command.
