name: Uhc
version: '${project.version}'
main: archietech.uhc.Uhc
api-version: 1.18
description: UHC Plugin
website: https://www.github.com/adrytech/UHC
author: [Alessandro De Iturbe, Delucchi Adriano]
